// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoAPIEstudo.Infraestruture.Contexto;

namespace ProjetoAPIEstudo.Infraestruture.Migrations
{
    [DbContext(typeof(ProjetoAIEstudoContexto))]
    [Migration("20210821231739_criarTabelas")]
    partial class criarTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoAPIEstudo.Entidade.Entidade.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Residencial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("tb_Cliente");
                });

            modelBuilder.Entity("ProjetoAPIEstudo.Entidade.Entidade.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("Id_Cliente");

                    b.ToTable("tb_Endereco");
                });

            modelBuilder.Entity("ProjetoAPIEstudo.Entidade.Entidade.Requerente", b =>
                {
                    b.Property<int>("IdRequerente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailRequerente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Veiculo")
                        .HasColumnType("int");

                    b.Property<string>("NomeRequerente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRequerente");

                    b.HasIndex("Id_Veiculo");

                    b.ToTable("tb_Requerente");
                });

            modelBuilder.Entity("ProjetoAPIEstudo.Entidade.Entidade.Veiculo", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("NomeVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVeiculo");

                    b.HasIndex("Id_Cliente");

                    b.ToTable("tb_Veiculo");
                });

            modelBuilder.Entity("ProjetoAPIEstudo.Entidade.Entidade.Endereco", b =>
                {
                    b.HasOne("ProjetoAPIEstudo.Entidade.Entidade.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Id_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoAPIEstudo.Entidade.Entidade.Requerente", b =>
                {
                    b.HasOne("ProjetoAPIEstudo.Entidade.Entidade.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("Id_Veiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoAPIEstudo.Entidade.Entidade.Veiculo", b =>
                {
                    b.HasOne("ProjetoAPIEstudo.Entidade.Entidade.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Id_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
